# Generated by Django 3.0b1 on 2019-10-29 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanslate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expungement_petition_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expugement_template_user_profiles', to='cleanslate.PetitionTemplate')),
                ('sealing_petition_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sealing_petition_template_user_profiles', to='cleanslate.PetitionTemplate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
