# Generated by Django 3.0b1 on 2019-10-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanslate', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitiontemplate',
            name='data',
            field=models.BinaryField(editable=True),
        ),
    ]
