# Generated by Django 2.2.6 on 2019-11-08 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=300)),
                ('docket_num', models.CharField(max_length=20)),
                ('court', models.CharField(choices=[('CP', 'CP'), ('MDJ', 'MDJ')], max_length=3)),
                ('url', models.URLField(null=True)),
                ('record_type', models.CharField(choices=[('SUMMARY_PDF', 'SUMMARY_PDF'), ('DOCKET_PDF', 'DOCKET_PDF')], max_length=30)),
                ('fetch_status', models.CharField(choices=[('NOT_FETECHED', 'NOT_FETCHED'), ('FETCHING', 'FETCHING'), ('FETCHED', 'FETCHED'), ('FETCH_FAILED', 'FETCH_FAILED')], default='NOT_FETCHED', max_length=100)),
                ('file', models.FileField(null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
