# Generated by Django 2.2.6 on 2019-11-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcerecord',
            name='docket_num',
            field=models.CharField(max_length=50),
        ),
    ]
