# Generated by Django 2.2.6 on 2019-11-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujs', '0002_auto_20191108_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcerecord',
            name='caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sourcerecord',
            name='court',
            field=models.CharField(blank=True, choices=[('CP', 'CP'), ('MDJ', 'MDJ')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sourcerecord',
            name='docket_num',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sourcerecord',
            name='fetch_status',
            field=models.CharField(choices=[('NOT_FETCHED', 'NOT_FETCHED'), ('FETCHING', 'FETCHING'), ('FETCHED', 'FETCHED'), ('FETCH_FAILED', 'FETCH_FAILED')], default='NOT_FETCHED', max_length=100),
        ),
        migrations.AlterField(
            model_name='sourcerecord',
            name='record_type',
            field=models.CharField(blank=True, choices=[('SUMMARY_PDF', 'SUMMARY_PDF'), ('DOCKET_PDF', 'DOCKET_PDF')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sourcerecord',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
